name: Build Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run reusable workflow
        run: |
          # You can call the reusable workflow using GitHub CLI or another method if needed
